### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Cadynum** [CTH-AI/shrdlite-course-project#1]
Vem gör vad?
- [x] Interpreter any
- [x] Interpreter all
- [ ] interpreter the (med förfrågningar 
- [x] 1 eller 2 (eller fler) armar i webinterfacet?
- [x] om arm=1 använd de gamla rutinerna för prestanda
- [x] h för >=2 armar
